# custom tag that will be added to all saved df's and models. 
output_tag:
    'VBF_BDT'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/evp18/oct_21/CMSSW_10_6_8/src/HToEE/2017/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/evp18/oct_21/CMSSW_10_6_8/src/HToEE/2017/Data/'

mc_file_names:
    sig:
        VBF:
            #'2016': 'VBF_UL2017.root' #re-use 17 as 16 for now
            '2017': 'VBF_M125.root' 
            #'2018': 'VBF_UL2017.root' #re-use 17 as 18 for now
        #VH:
         #   '2017': 'VH_M125.root'
        #ggH:
         #   '2017': 'ggH_M125.root'
        #ttH:
        #    '2017': 'ttH_M125.root'
    bkg:
        ggH:
            '2017': 'ggH_M125.root'
        #Gjet20to40:
         #  '2017': 'GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root'
        #Gjet20toInf:
         #  '2017': 'GJet_Pt-20toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8.root'
        #Gjet40toInf:
        #   '2017': 'GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root'
        #QCD30to40:
         #  '2017': 'QCD_Pt-30to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root'
        #QCD30toInf:
         #  '2017': 'QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8.root' 
        #QCD40toInf:
         #  '2017': 'QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8.root'
        #Diphoton40to80:
         #  '2017': 'DiPhotonJetsBox_M40_80-sherpa.root'
        #Diphoton80toInf:
         #  '2017': 'DiPhotonJetsBox_MGG-80toInf_13TeV-sherpa.root'

data_file_names:
    Data:
        #'2016': 'Data_UL2016.root'
        '2017': 'Data.root'
        #'2018': 'Data_UL2018.root'


#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    VBF: 'Events'
    VH: 'Events'
    ggH: 'Events'
    ttH: 'Events'
    Gjet20to40: 'Events'
    Gjet20toInf: 'Events'
    Gjet40toInf: 'Events'
    QCD30to40: 'Events'
    QCD30toInf: 'Events'
    QCD40toInf: 'Events'
    Diphoton40to80: 'Events'
    Diphoton80toInf: 'Events'
    Data: 'Events'
    

#X variables to train with. Must be in nominal_vars (unless created from existing features)
train_vars:
    [ 'diphotonPt', 'diphotonMass', 'diphotonCosPhi', 'diphotonEta','diphotonPhi', 'diphotonSigmaMoM',
     'dijetMass', 'dijetAbsDEta', 'dijetDPhi', 'dijetCentrality',
     'dijetPt','dijetEta','dijetPhi','dijetMinDRJetPho','dijetDiphoAbsDEta',
     'leadPhotonEta', 'leadPhotonIDMVA', 'leadPhotonEn', 'leadPhotonPt', 'leadPhotonPhi',
     'leadJetPt', 'leadJetPUJID', 'leadJetBTagScore', 'leadJetMass',
     'leadJetDiphoDEta','leadJetDiphoDPhi','leadJetEn','leadJetEta','leadJetPhi',
     'subleadPhotonEta', 'subleadPhotonIDMVA', 'subleadPhotonPhi',
     'subleadPhotonEn','subleadPhotonPt', 
     'subleadJetDiphoDPhi','subleadJetDiphoDEta',
     'subleadJetPt', 'subleadJetPUJID', 'subleadJetBTagScore', 'subleadJetMass',
     'subleadJetEn','subleadJetEta','subleadJetPhi',
     'subsubleadJetEn','subsubleadJetPt','subsubleadJetEta','subsubleadJetPhi', 'subsubleadJetBTagScore', 
     'subsubleadJetMass',
     'metPt','metPhi','metSumET',
     'nSoftJets'
     
     #'diphotonPt', 'leadPhotonEta', 'subleadPhotonEta', 'leadPhotonIDMVA', 'subleadPhotonIDMVA','leadJetPt' , 'subleadJetPt', 'diphotonMass', 'dijetMass'
     #,'dijetAbsDEta', 'dijetDPhi', 'diphotonCosPhi'
     #,'leadJetPUJID', 'subleadJetPUJID'
     #,'subsubleadJetEn','subsubleadJetPt','subsubleadJetEta','subsubleadJetPhi'
     #, 'dijetCentrality', 'leadJetBTagScore', 'subleadJetBTagScore', 'subsubleadJetBTagScore'
     #, 'leadJetMass', 'leadPhotonEn','leadPhotonPt'
     #, 'subleadJetMass', 'subleadPhotonEn','subleadPhotonPt',
     #'leadPhotonPhi','leadJetDiphoDEta','leadJetDiphoDPhi','leadJetEn','leadJetEta','leadJetPhi',
     #'subleadPhotonPhi',
     #'subsubleadPhotonEn',
     #'subsubleadJetMass',
     #'subsubleadPhotonPt','subsubleadPhotonEta','subsubleadPhotonPhi',
     #'subleadJetDiphoDPhi',
     #'subleadJetDiphoDEta','subleadJetEn','subleadJetEta','subleadJetPhi',
     #'subsubleadPhotonIDMVA',
     #'diphotonEta','diphotonPhi','dijetPt','dijetEta','dijetPhi','dijetMinDRJetPho','dijetDiphoAbsDEta',
     #'nSoftJets', 'diphotonSigmaMoM',
     #'leadTrkEn','leadTrkMass','leadTrkPt','leadTrkEta','leadTrkPhi','leadPhotonSigmaE',
     #'leadPhotonHoE','leadPhotonPfRelIsoAll','leadPhotonPfRelIsoChg','leadPhotonR9','leadPhotonSieie',
     #'leadPhotonElectronVeto','leadPhotonPixelSeed','leadPhotonElectronIdx','leadPhotonJetIdx','leadJetQGL','leadJetID',
     #'leadTrkDxy','leadTrkDz','leadTrkPfRelIso03All','leadTrkPfRelIso03Chg','leadTrkMiniPFRelIsoAll',
     #'leadTrkMiniPFRelIsoChg','leadTrkFromPV','leadTrkIsHighPurityTrack','leadTrkIsPFcand','leadTrkIsFromLostTrack',
     #'subleadTrkEn','subleadTrkMass','subleadTrkPt','subleadTrkEta','subleadTrkPhi','subleadPhotonSigmaE','subleadPhotonHoE',
     #'subleadPhotonPfRelIsoAll','subleadPhotonPfRelIsoChg','subleadPhotonR9','subleadPhotonSieie','subleadPhotonElectronVeto',
     #'subleadPhotonPixelSeed','subleadPhotonElectronIdx','subleadPhotonJetIdx','subleadJetQGL','subleadJetID',
     #'subleadTrkDxy','subleadTrkDz','subleadTrkPfRelIso03All','subleadTrkPfRelIso03Chg','subleadTrkMiniPFRelIsoAll',
     #'subleadTrkMiniPFRelIsoChg','subleadTrkFromPV','subleadTrkIsHighPurityTrack','subleadTrkIsPFcand','subleadTrkIsFromLostTrack',
     #'subsubleadTrkEn','subsubleadTrkMass','subsubleadTrkPt','subsubleadTrkEta','subsubleadTrkPhi','subsubleadPhotonSigmaE',
     #'subsubleadPhotonHoE','subsubleadPhotonPfRelIsoAll','subsubleadPhotonPfRelIsoChg','subsubleadPhotonR9','subsubleadPhotonSieie',
     #'subsubleadPhotonElectronVeto','subsubleadPhotonPixelSeed','subsubleadPhotonElectronIdx','subsubleadPhotonJetIdx',
     #'subsubleadJetQGL','subsubleadJetID',
     #'subsubleadJetPUJID',#'subsubleadTrkDx',
     #'subsubleadTrkDz','subsubleadTrkPfRelIso03All',
     #'subsubleadTrkPfRelIso03Chg','subsubleadTrkMiniPFRelIsoAll','subsubleadTrkMiniPFRelIsoChg','subsubleadTrkFromPV',
     #'subsubleadTrkIsHighPurityTrack','subsubleadTrkIsPFcand','subsubleadTrkIsFromLostTrack',
     #'diphotonSigmaMoM','dijetDiphoAbsDPhiTrunc',
     #'metPt','metPhi','metSumET' #,'metSignificance' #'PhotonIDSF','TriggerSF'
     #, 'subleadPhotonPtOvM' #'dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     #'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     #'leadJetDieleDPhi', 'subleadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDEta',
     #'leadElectronPtOvM', 'subleadElectronPtOvM', 'dielectronPt',
     #'leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL', 
     #'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
     #'subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL',
     #'nSoftJets', #'leadJetBTagScore', 'subleadJetBTagScore', 'subsubleadJetBTagScore'
     #'leadJetPUJID','subleadJetPUJID', 'subsubleadJetPUJID','leadJetID','subleadJetID','subsubleadJetID'
     #'nSoftJets' ,'metSumET', 'metPt', 'metPhi', 'leadJetBTagScore', 'subleadJetBTagScore', 'subsubleadJetBTagScore'
    ] 

vars_to_add:
    #'subsubleadJetCentrality':

#preselection that will be applied to all samples
preselection:
    'diphotonMass > 100 and diphotonMass < 180 and leadPhotonPtOvM > 0.333 and subleadPhotonPtOvM > 0.25'
    #and dijetMass>250 and leadJetPt>40 and subleadJetPt>25'  # specific for VBF

#reweight_cr: #looser selection (CR region is taken from this, but not exactly the same as this)
  #  'diphotonMass > 80 and diphotonMass < 150 and leadPhotonPtOvM > 0.333 and subleadPhotonPtOvM > 0.25 and dijetMass>250  #and leadJetPt>40 and subleadJetPt>25 and (leadElectronCharge == -subleadElectronCharge)'


