# custom tag that will be added to all saved df's and models. 
output_tag:
    'VBF_DNN'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/evp18/oct_21/CMSSW_10_6_8/src/HToEE/2017/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/evp18/oct_21/CMSSW_10_6_8/src/HToEE/2017/Data/'

mc_file_names:
    sig:
        VBF:
           # '2016': 'VBF_UL2017.root' #re-use 2017 in 2016 for noe
            '2017': 'VBF_M125.root'
           # '2018': 'VBF_UL2017.root' #re-use 2017 in 2018 for noe
    bkg:
        ggH:
            '2017': 'ggH_M125.root'
       # DYMC:
        #    '2016': 'DY_UL2016.root'
        #    '2017': 'DY_UL2017.root'
        #    '2018': 'DY_UL2018.root'

       # TT2L2Nu:
        #    '2016': 'TTLNu_UL2016.root'
        #    '2017': 'TTLNu_UL2017.root'
        #    '2018': 'TTLNu_UL2018.root'
       # TTSemiL:
        #    '2016': 'TTSemi_UL2016.root'
        #    '2017': 'TTSemi_UL2017.root'
        #    '2018': 'TTSemi_UL2017.root' #dont have 2018 atm
       # EWKZ:
        #    '2016': 'EWKZ_2016.root'
        #    '2017': 'EWKZ_2017.root'
        #    '2018': 'EWKZ_2018.root'

data_file_names:
    Data:
        #'2016': 'Data_UL2016.root'
        '2017': 'Data.root'
        #'2018': 'Data_UL2018.root'

#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    VBF: 'Events'
    ggH: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    TT2L2Nu: 'Events'
    TTSemiL: 'Events'
    EWKZ: 'Events'

#X variables to train with (4 vectors of jets... and maybe photons... anything else that is low-level and maybe useful?)
object_vars:
    [['leadJetPt', 'leadJetMass','leadJetEn','leadJetEta','leadJetPhi'],
     ['leadPhotonEta', 'leadPhotonEn', 'leadPhotonPt', 'leadPhotonPhi'],
     ['subleadPhotonEta', 'subleadPhotonPhi','subleadPhotonEn','subleadPhotonPt'],
     ['subleadJetPt', 'subleadJetMass','subleadJetEn','subleadJetEta','subleadJetPhi'],
     ['subsubleadJetEn','subsubleadJetPt','subsubleadJetEta','subsubleadJetPhi','subsubleadJetMass']
    ]
    #[['leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL'], 
     #['subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL'],
     #['subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL']
    #]

event_vars:
    ['diphotonPt', 'diphotonMass', 'diphotonCosPhi', 'diphotonEta','diphotonPhi', 'diphotonSigmaMoM',
     'dijetMass', 'dijetAbsDEta', 'dijetDPhi', 'dijetCentrality',
     'dijetPt','dijetEta','dijetPhi','dijetMinDRJetPho','dijetDiphoAbsDEta',
     'leadJetPUJID', 'leadJetBTagScore', 'leadJetDiphoDEta','leadJetDiphoDPhi',
     'leadPhotonIDMVA',
     'subleadJetPUJID', 'subleadJetBTagScore','subleadJetDiphoDPhi','subleadJetDiphoDEta',
     'subleadPhotonIDMVA',
     'subsubleadJetBTagScore',
     'metPt','metPhi','metSumET',
     'nSoftJets'
    ]
   # ['dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
    # 'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
    # 'leadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDPhi', 'subleadJetDieleDEta',
    # 'leadElectronPtOvM', 'subleadElectronPtOvM', 'dielectronPt'
    #]

train_vars: #all vars for plotting inputs. Can just get this from above vars
    [ 'diphotonPt', 'diphotonMass', 'diphotonCosPhi', 'diphotonEta','diphotonPhi', 'diphotonSigmaMoM',
     'dijetMass', 'dijetAbsDEta', 'dijetDPhi', 'dijetCentrality',
     'dijetPt','dijetEta','dijetPhi','dijetMinDRJetPho','dijetDiphoAbsDEta',
     'leadPhotonEta', 'leadPhotonIDMVA', 'leadPhotonEn', 'leadPhotonPt', 'leadPhotonPhi',
     'leadJetPt', 'leadJetPUJID', 'leadJetBTagScore', 'leadJetMass',
     'leadJetDiphoDEta','leadJetDiphoDPhi','leadJetEn','leadJetEta','leadJetPhi',
     'subleadPhotonEta', 'subleadPhotonIDMVA', 'subleadPhotonPhi',
     'subleadPhotonEn','subleadPhotonPt', 
     'subleadJetDiphoDPhi','subleadJetDiphoDEta',
     'subleadJetPt', 'subleadJetPUJID', 'subleadJetBTagScore', 'subleadJetMass',
     'subleadJetEn','subleadJetEta','subleadJetPhi',
     'subsubleadJetEn','subsubleadJetPt','subsubleadJetEta','subsubleadJetPhi', 'subsubleadJetBTagScore', 
     'subsubleadJetMass',
     'metPt','metPhi','metSumET',
     'nSoftJets'
    ]

  #  ['dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
   #  'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
   #  'leadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDPhi', 'subleadJetDieleDEta',
   #  'leadElectronPtOvM', 'subleadElectronPtOvM', 'dielectronPt',
   #  'leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL', 
   #  'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
   #  'subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL'
   # ] 
    

vars_to_add:

#preselection that will be applied to all samples
preselection:
    'diphotonMass > 100 and diphotonMass < 180 and leadPhotonPtOvM > 0.333 and subleadPhotonPtOvM > 0.25'
    #'dielectronMass > 110 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25 and dijetMass>250 and leadJetPt>40 and subleadJetPt>30'
